version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    networks:
      passwordmanager:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  server:
    image: password-manager
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    depends_on:
      - postgres
    networks:
      passwordmanager:
    ports:
      - "8080:8080"
    environment:
      CONN_STRING: host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/api/v1/passwords", "-O", "-", "-q"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 1s

networks:
  passwordmanager:

volumes:
  postgres-data:
