/*
 * Password manager
 *
 * A simple manager for storing your passwords
 *
 * API version: 1.0.0
 * Contact: korotkov.ivan.s@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	ApiV1PasswordsGet(http.ResponseWriter, *http.Request)
	ApiV1PasswordsIdDelete(http.ResponseWriter, *http.Request)
	ApiV1PasswordsIdGet(http.ResponseWriter, *http.Request)
	ApiV1PasswordsIdPut(http.ResponseWriter, *http.Request)
	ApiV1PasswordsPost(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	ApiV1PasswordsGet(context.Context) (ImplResponse, error)
	ApiV1PasswordsIdDelete(context.Context, int32) (ImplResponse, error)
	ApiV1PasswordsIdGet(context.Context, int32) (ImplResponse, error)
	ApiV1PasswordsIdPut(context.Context, int32, Password) (ImplResponse, error)
	ApiV1PasswordsPost(context.Context, Password) (ImplResponse, error)
}
